### ISSUE TITLE
Batch simulation / parameter optimization (possibly using CFG format)

### ISSUE THREAD

**Issue by samnemo** [Neurosim-lab/netpyne#108]
For large batches of simulations I find it useful to use Python's ConfigFile writer/reader - then my python code reads and generates cfg files with parameter sweeps (for example see /u/samn/m1dyst/conf.py , /u/samn/m1dyst/batch.py ) ... this may be easier than writing all parameters in a .py file - since config file is generally flat (with sections) and is therefore easier to generate cfg file easily (+Python supports this). Could such a feature be integrated with NetPyne? Yes, but does it fit NetPyne's design philosophy?

**Comment by salvadord** [comment]
I'm planning on providing some code for batch sims / param optimization using netpyne -- not sure yet if makes sense to integrate with netpyne, or provide as some example wrapper code. 
I've seenn your CFG code so that, or a variation of it, could definitely be used.

**Comment by salvadord** [comment]
- Create sep module batch.py ?
- Add support for analysis of batch results

**Comment by salvadord** [comment]
Check possible integration with pypet - http://journal.frontiersin.org/article/10.3389/fninf.2016.00038/full

**Comment by salvadord** [comment]
check http://deap.readthedocs.io/en/master/ for param optim
