### ISSUE TITLE
Separation of sim and data

### ISSUE THREAD

**Issue by samnemo** [Neurosim-lab/netpyne#109]
I sometimes separate simulation (sim.py) and simulation-data-reading code (simdat.py) - that way I don't have to load the whole sim to read sim data. However, to properly analyze simulation data, certain data structures are needed (number of cells, cell IDs, cell types, etc.). Is it easy for users to add the key data structures to NetPyne structures that get saved? Probably...

**Comment by salvadord** [comment]
Netpyne data is separated into:
- netParams: network high-level specifications
- simConfig: simulation configuration
- net: network instance, including info on all pops, cells, conns, stims etc
- simData: simulation output data, including spkt times, voltage traces, etc

It is already possible to save and load each of these separately. For most of the graphs you will need the net and simData structures.
