### ISSUE TITLE
Plotting options

### ISSUE THREAD

**Issue by samnemo** [Neurosim-lab/netpyne#111]
Options for raster plots:
- [ ] Adjust size of markers
- [x] Colors for different populations (eg red for E, blue for SOM, green for PV)
- [x] Text labels indicating which population on vertical axis

We have some code for this on neurosim but not currently fit into NetPyne

Spike hist:
- [x] invert axis

Conn matrix:
- [ ] Option to choose color maps for individual populations (e.g. red for excitatory connections and blue for inhibitory connections). 
- [ ] Option to detect exc vs inh conns (by synMech label or 'e') and plot using different color map (red vs blue) -- similar to 2DNet conns

plot2DNet:
- [ ] invert axis

All plots:
- [ ] legend outside shows properly (depends on computer?)

**Comment by salvadord** [comment]
Ok, will provide markersize and colors as optional arguments, and add option to include pop labels in vertical axis -- will check neurosim code when get to it.
