### ISSUE TITLE
Access to classes/templates functions

### ISSUE THREAD

**Issue by samnemo** [Neurosim-lab/netpyne#112]
Any way to allow access to classes/templates defined in py/hoc files - as they were written - ? Some member functions may be useful...

**Comment by salvadord** [comment]
it might be possible to copy over the methods defined in the py/hoc files, so that they can be called from netpyne. Will need to check if possible and how to integrate so makes sense.

**Comment by salvadord** [comment]
Example by Sam:
so axonal density of some channels is scaled by a factor
axon.gbar_nax = gbar_nax * nax_gbar_axonm
   axon.gbar_kdr = gbar_kdr * kdr_gbar_axonm
   axon.gbar_kap = gbar_kap * kap_gbar_axonm

nax_gbar_axonm is a param, gbar_nax is a param
after the cell has been created, if u wanna modify, you change global and call func

Salvador:so recreating the actual functions would require parsing the original script and generating new funcs adapted to netpyne format (but wouldn't really be part of netpyne per se, just funcs still that work -- however lot of work and not even sure doable in such way that works generically

however somethign that I could do is at least try to import the global variables so u can use them within netpyne

**Comment by salvadord** [comment]
Added importing of global variables
