### ISSUE TITLE
Shared Netstims

### ISSUE THREAD

**Issue by samnemo** [Neurosim-lab/netpyne#113]
Not sure there's a way to specify 
1. inputs who's statistics change over time - sometimes do this in NEURON via events - sometimes pre-generate the sequence
2. NetStims that are shared - having access to NetStim/NetCon pointers makes it easy to check that one Stim applies to a set of targets - in NetPyne seem to specify this via population of cells - 1 NetStim per target cell - adjustable?

**Comment by salvadord** [comment]
1. Yes, there is an issue (#33) to provide different types of inputs, including time-varying etc -- already have some code from cliff's student to do part of it.
Also, not that when creating stims you can specify all params using string-based functions, so you can specify eg. gauss of uniform distributions, or even params as a function of cell properties (eg. depth). 

2. There's 2 ways to create Netstims (as a population or as a stim) although in both cases it creates 1 netstim per target cell. I will add option to have shared netstim
