### ISSUE TITLE
What is the primary, unique id of the cellRule/cellModel?

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#129]
In the HybridTutorial it seems to be cellModel:

```
netParams.addPopParams('PYR_HH', {'cellModel': 'HH', 'cellType': 'PYR', 'numCells': 50})
netParams.addPopParams('PYR_Izhi', {'cellModel': 'Izhi2007b', 'cellType': 'PYR', 'numCells': 50})
```

but in M1 it seems to be cellType

```
netParams.addPopParams('IT_L5B', {'cellModel': 'Izhi2007b', 'cellType': 'IT',  'ynormRange': [0.52, 0.77], 'density': 40e3}) #  L5B IT
netParams.addPopParams('PT_L5B', {'cellModel': 'Izhi2007b', 'cellType': 'PT',  'ynormRange': [0.52, 0.77], 'density': 40e3}) #  L5B PT
```

here, the parameter cellModel is not even set in the cellRule:

```
cellRule = {'conds': {'cellType': 'IT'}, 'secs': {}}
```

I can see that the way popparams are set up means "try to find a cellRule which satisfies all of these conditions", but this is not ideal, especially when you know there has to be exactly one cellRule that satisfies these conditions.

It would be better to (consistently) use the one unique id you do have for cellRules when you add them to the params:

```
netParams.addCellParams('IT', cellRule)
```

**Comment by salvadord** [comment]
@pgleeson - The unique id / label is arbitrary and depends on what you want to do.

There can be several cell rules that apply to the same cell. That way for example you can create a rule that applies to all 'cellType':'IT' (if you have a unique 'cellModel' in the net), or 2 different rules that apply to {'cellType':'IT', 'cellModel':'HH'} and {'cellType':'IT', 'cellModel':'Izhi'}.

Also, you might want to apply certain properties only to a subset of cells, eg. after creating the standard cell rules, you could modify the morphology or biophysics only of cells within a certain cortical depth: 'conds': {'y': [400, 600]} 

Cell rules are applied additively, such that later rules modify existing values or add elements if these are missing.

**Comment by pgleeson** [comment]
@salvadord That's a perfectly fine way to choose form a set of cell instances where some subset may or may not have some properties, but the specification of which cell parameter set to use for a specific population is different: there has to be one and only one cell/cellParam that is used for the population. This suggests the best way to identify this is with the id in:

     netParams.addCellParams('IT', cellRule)   # the "cellParam id"

because there can only ever be one of these. The approach of "try to find one of the cells based on this set of conditions" is a bit loose when it comes to specifying which cell is in a population. Also, there's nothing to stop a user adding multiple cells with identical cellType & cellModel values but different cellParam ids... In that case which one will be used in the population is not specified...

**Comment by salvadord** [comment]
The initial concept that Ben and I came up with was precisely not having to define properties in terms of populations. So, there doesn't necessarily have to e on cellParam per population. The user can chose to make the same cellParam rule apply to several populations; or several cellParam rules to subsets of a population. Cells have a set of tags (popLabel, cellModel, cellType, x,y,z etc) and its up to the user to specify how to set properties based on these. I understand it s a bit loose, but its also much more flexible, which is what we were looking for. In most cases the user will decide to apply one cellParam rule per cellType or popLabel, but we don't want to necessarily enforce that. 

If the user adds two cellParam rules with the same conditions (eg. cellType and CellModel) they will both be applied in sequential order, overwriting the previous one where overlaps happen. Using exactly the same conditions doesnt' obviously make sense and netpyne could detect and issue an error/warning. However, it is conceivable that the user may want to apply a general rule to all cellType: 'IT', and then, using a second rule, modify a single specific parameter (eg. channel conductance) of all cells within cortical depth [200,400]. These 2 rules may end up applying to the same cell (cellType IT with y [200,400]), and thats the kind of flexibility we wanted to allow. 

Internal checks can be added to make sure that eg. all cells match at least one of the cellParam rules.
