### ISSUE TITLE
Ensure all of gnabar/gkbar/ena etc. set on cellRule['secs']['soma']['mechs']['hh'], or use defaults

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#132]
Similar to #130, if some of gnabar/ena/gl/ge are left out when setting on mech = hh, Netpyne should fill in the defaults, so any are accessible with e.g. secs.soma.mechs.hh.gnabar.

**Comment by salvadord** [comment]
moved to issue #130
