### ISSUE TITLE
Allow either pt3d or diam/L, not both

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#133]
Neuron allows you to set diam & L & then add pt3d points. Netpyne should allow only one or the other, and probably generate pt3d points if diam & L are used. 

This is an example of the inconsistency that can occur: https://github.com/Neurosim-lab/netpyne/blob/d166081f664ce2e4c8ec96f1015c3e85acfa1c00/examples/HybridTut/HybridTut.py#L36

**Comment by salvadord** [comment]
moved to issue #35
