### ISSUE TITLE
Allow sec and loc to be specified for pre cell in _addCellConn()

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#147]
It seems only the sec/loc for specifying where to connect on the **postsynaptic** multicompartmentalcell can be specified in [_addCellConn()](https://github.com/Neurosim-lab/netpyne/blob/061104b7d242c22e855ef441d21532ef6b7d633a/netpyne/network.py#L651). It would be great to be able to specify this location on the presynaptic cell too (or does it exist already?)

I need to call this method directly (as opposed to setting up with dicts) in the NeuroML import method: https://github.com/Neurosim-lab/netpyne/blob/cdfeb242f63121e54055d8c61c05b0c3782769e9/netpyne/simFuncs.py#L1974

**Comment by salvadord** [comment]
As you know the way cells are connected in parallel Neuron is using pc.gid_connect(), which for the presyn cell only takes a cell gid. The way to associate a different presyn source of spikes is to specify it when you associated the gid with the cell using the pc.cell() command. 

netpyne allows to specify a different source of spikes for a cell by setting the 'spikeGenLoc' param in the corresponding section. See the Traub or Friesen models for examples: http://neurosimlab.org/netpyne/advanced.html#traub-model 
http://neurosimlab.org/netpyne/advanced.html#friesen-model

Please, let me know if that works for what you need to do, or you need something else. thx

**Comment by pgleeson** [comment]
That should work... Does it mean though for any cell there can only be one spike source in the whole cell? That should be ok too, but I'll have to test the imported NML that the pre locations on a cell are all the same...

**Comment by salvadord** [comment]
Yes, think each cell can only have 1 spike generation site -- I believe that's a constraint imposed by Neuron, but there might some workaround -- let me know if you need it and I'll check with Mike Hines if some alternative.
