### ISSUE TITLE
Global disabling of all graphics

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#150]
One of the issues I found when testing on Travis ( #37), and also when running Netpyne scripts remotely was that matplotlib was required, and that some graphical elements were initialised leading to errors related to no display for windows.

It would be great to be able to set one global variable in netpyne to say: ignore all plotting etc. *and don't even try to import matplotlib etc*. This would allow scripts such as this:  https://github.com/Neurosim-lab/netpyne/blob/master/examples/HHTut/HHTut_run.py to search for a command line arg (-nogui) and set that one global variable in netpyne, as opposed to individually disabling gui elements, e.g. https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/master/NetPyNE/HHSmall/HH_run.py

**Comment by salvadord** [comment]
@pgleeson:
You can now do this to disable graphics:
import netpyne
netpyne.__gui__ = False
