### ISSUE TITLE
Check support for setting ion properties, ena, cai, cao etc.

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#151]
I've implemented some support for this here: https://github.com/Neurosim-lab/netpyne/blob/64759a574ca4ef17a7ff48ad8e3ae45aa0256be9/netpyne/cell.py#L182, e.g. setting ena, cai, cao etc.

This should be checked by @salvadord to make sure it's best practice and then maybe added to docs.

**Comment by salvadord** [comment]
- Checked and added to the docs; also added to import function so automatically imports e param
- Still need to check if other params need to be imported too
