### ISSUE TITLE
incorrect time axis (x axis), inverted y axis and overlapping y axis labels for plotSpikeHist

### ISSUE THREAD

**Issue by jingxlim** [Neurosim-lab/netpyne#163]
- X axis sometimes malfunctions, for example when tstop is set to 'odd' numbers
- Y axis is inverted on some set ups but not others
- Y axis labels [Avg cell firing rate (Hz)] tend to overlap when overlay=False. Suggestion: plot a single y axis label regardless of the number of spike histograms plotted.

**Comment by salvadord** [comment]
fixed by commit: fb875a47e72690ad7a2f03093ac5794f825e1526
