### ISSUE TITLE
Missing inc files in doc/source/code/mod

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#181]
A number of *.inc files are required to compile the mod files in https://github.com/Neurosim-lab/netpyne/tree/master/doc/source/code/mod, e.g. https://github.com/Neurosim-lab/netpyne/blob/master/doc/source/code/mod/A.mod#L16, but are not there...

**Comment by joewgraham** [comment]
All mod files compile properly now.
