### ISSUE TITLE
Fix bug using importCellParams in for loop

### ISSUE THREAD

**Issue by salvadord** [Neurosim-lab/netpyne#191]
if use >1 calls to importCellParams within same for loop, successive calls import the same cell params as 1st one.

**Comment by salvadord** [comment]
check if this is still happening (posted 2 years ago)

**Comment by joewgraham** [comment]
I tested by copying HHCellFile.py into HHCellFile_1.py and HHCellFile_2.py and modifying soma length in the latter.  Then I ran the following code to demonstrate that there is no problem with using importCellParams in a for loop:

    from netpyne import specs, sim
    
    # Network parameters
    netParams = specs.NetParams() 
    
    ## Population parameters
    netParams.popParams['HH_1'] = {'cellType': 'PYR', 'numCells': 5, 'cellModel': 'HH_1'}
    netParams.popParams['HH_2'] = {'cellType': 'PYR', 'numCells': 5, 'cellModel': 'HH_2'}
    
    for file_ind, cell_file in enumerate(['HHCellFile_1.py', 'HHCellFile_2.py']):
    
        print(cell_file)
        label = 'HH_' + str(file_ind + 1)
        print(label)
        print('=================')
    
        cellRule = netParams.importCellParams(label=label, conds={'cellType': 'PYR', 'cellModel': label}, fileName=cell_file, cellName='HHCellClass', importSynMechs=False)
    
        print(cellRule)
        print('\n\n')
    
    
    # Simulation options
    simConfig = specs.SimConfig()                   
    simConfig.duration = 100          
    simConfig.dt = 0.025                
    simConfig.verbose = 0           
    simConfig.recordTraces = {'V_soma':{'sec':'soma','loc':0.5,'var':'v'}}  
    simConfig.recordStep = 1            
    simConfig.filename = 'model_output'  
    simConfig.savePickle = False  
    simConfig.analysis['plotTraces'] = {'include': [0,5]}
    
    
    # Create network and run simulation
    sim.createSimulateAnalyze(netParams = netParams, simConfig = simConfig)
    
    for cell in sim.net.allCells:
        print(cell['secs']['soma']['geom']['L'])
