### ISSUE TITLE
Cycle through hosts from last used when assigning cells in Parallel Neuron

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#196]
This output from generation of a network with 4 cell type/populations and 13 (multicompartmental) cells total (10+1+1+1) shows a skewed distribution of cells per host:
```
(INFO) NRN Output >>> Creating network of 4 cell populations on 8 hosts...
(INFO) NRN Output >>>   Number of cells on node 1: 2 
(INFO) NRN Output >>> Creating connections for Proj0syn0_CG3D_L23PyrRS_CG3D_L23PyrRS (projection): CG3D_L23PyrRS->CG3D_L23PyrRS via Syn_AMPA_SupPyr_SupPyr
(INFO) NRN Output >>>   Number of cells on node 2: 1 
(INFO) NRN Output >>> Creating connections for Proj0syn0_CG3D_L23PyrRS_CG3D_L23PyrRS (projection): CG3D_L23PyrRS->CG3D_L23PyrRS via Syn_AMPA_SupPyr_SupPyr
(INFO) NRN Output >>>   Number of cells on node 7: 1 
(INFO) NRN Output >>> Creating connections for Proj0syn0_CG3D_L23PyrRS_CG3D_L23PyrRS (projection): CG3D_L23PyrRS->CG3D_L23PyrRS via Syn_AMPA_SupPyr_SupPyr
(INFO) NRN Output >>>   Number of cells on node 3: 1 
(INFO) NRN Output >>> Creating connections for Proj0syn0_CG3D_L23PyrRS_CG3D_L23PyrRS (projection): CG3D_L23PyrRS->CG3D_L23PyrRS via Syn_AMPA_SupPyr_SupPyr
(INFO) NRN Output >>>   Number of cells on node 5: 1 
(INFO) NRN Output >>> Creating connections for Proj0syn0_CG3D_L23PyrRS_CG3D_L23PyrRS (projection): CG3D_L23PyrRS->CG3D_L23PyrRS via Syn_AMPA_SupPyr_SupPyr
(INFO) NRN Output >>>   Number of cells on node 6: 1 
(INFO) NRN Output >>> Creating connections for Proj0syn0_CG3D_L23PyrRS_CG3D_L23PyrRS (projection): CG3D_L23PyrRS->CG3D_L23PyrRS via Syn_AMPA_SupPyr_SupPyr
(INFO) NRN Output >>>   Number of cells on node 4: 1 
(INFO) NRN Output >>> Creating connections for Proj0syn0_CG3D_L23PyrRS_CG3D_L23PyrRS (projection): CG3D_L23PyrRS->CG3D_L23PyrRS via Syn_AMPA_SupPyr_SupPyr
(INFO) NRN Output >>>   Number of cells on node 0: 5 
(INFO) NRN Output >>>   Done; cell creation time = 0.22 s.
```
Basically for each new population it starts adding at node 0. It would be better to add the next cell to the next host in line..

**Comment by pgleeson** [comment]
Working on a solution for this here: https://github.com/Neurosim-lab/netpyne/commit/9c2f31f7bd7d642eff83946b404c09070d96926d. Requires futher testing.

@salvadord is there anywhere else that needs to know about which cells goes on which host?

**Comment by salvadord** [comment]
Great, actually had an issue for this: #41 

I believe there's no other place that requires updating. One possible change for consistency would be to use sim.next_host (instead of a global) and initialize sim.next_host=0 in sim.initialize() func. 

If you tested it and it works ok, go ahead with PR and I'll merge on development. Thanks!

**Comment by salvadord** [comment]
@pgleeson - I plan to release version in the next few days... is this ready? I would like to include the new cell assigning code. thx

**Comment by pgleeson** [comment]
@salvadord I have a few more updates to do in my branch related to nml before it's stable. Might be best for you to grab the changes from https://github.com/Neurosim-lab/netpyne/commit/9c2f31f7bd7d642eff83946b404c09070d96926d, test them in development and merge to master with the rest if you're happy with them.

**Comment by salvadord** [comment]
Added to commit ab3ae7e

**Comment by pgleeson** [comment]
For me this is fixed, your changes in development work fine @salvadord. 

Clearly there are other optimisations in terms of balancing cells of different sizes/syn numbers more evenly across hosts, but #41 is a better place to record these.
