### ISSUE TITLE
Add setup.py

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#2]
It would be good to be able to install the package for use in any other python scripts. The steps for this are usually:

- [x] move main python scripts to sub folder named netpyne
- [x] move examples to folder named examples (and include run_hhTut.py etc to run them directly)
- [x] create a setup.py (good indication for outline [here](https://github.com/NeuralEnsemble/PyNN/blob/master/setup.py))

Setting it up in this way will also facilitate linking to [Travis-CI](https://travis-ci.org)

See [here](https://github.com/OpenSourceBrain/SmithEtAl2013-L23DendriticSpikes/blob/master/.travis.yml) for an example of a script that installs Neuron and you could even test running of the examples at every commit

@salvadord  I'm happy to try this out, but since it will involve moving a number of files, let me know if you'll do it first and I can add any updates.

**Comment by salvadord** [comment]
In the documentation ([http://neurosimlab.org/netpyne/install.html]) I give instructions on how to clone and add netpyne path to $PYTHONPATH, which is the only thing needed to make it usable by any other python scripts (ie. can do `import netpyne`). 

However, I have been looking into setup.py to automatize the process (actually an intern is looking into it). I will check out these links and try to do it, thanks.

Regarding the folder structure, I guess it makes sense to separate the examples into separate folder. So just to be clear, you suggest having folders under the root: 'netpyne' and 'examples' ? In that case, when cloning the repo wouldn't you need an additional root folder name that includes both? Would it be ok to include the 'examples' as a subfolder of 'netpyne'?

**Comment by pgleeson** [comment]
Yes, I managed to get it running with setting $PYTHONPATH.

I don't think there are any hard and fast rules for locating the examples folder. Andrew puts it at top level here: https://github.com/NeuralEnsemble/PyNN; it's in a subfolder here: https://github.com/NeuralEnsemble/libNeuroML/tree/master/neuroml. I find that it's easier to spot that there are examples if it's at the top level.

**Comment by salvadord** [comment]
Ok I changed the folder structure as you suggested and also created setup.py etc (so now can install via pip install netpyne). Much easier to install now! thanks for suggestion
I checked that the examples and M1 still works. At some point I will check out the Travis-CI tool for automatic testing.

**Comment by pgleeson** [comment]
Works fine for me now!
