### ISSUE TITLE
Add option to record spikes only from cells

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#208]
While there is the option of recording voltage & other continuous traces from cells and recording spikes from inputs, there does not seem to be currently an option to only record spikes from selected cells. 

This is [possible in LEMS](https://github.com/NeuroML/NeuroML2/blob/development/LEMSexamples/LEMS_NML2_Ex23_Spiketimes.xml#L66) and will be crucial for running large scale point neuron networks (e.g. Potjans and Diesman) converted PyNN->NeuroML2->NetPyNE.

**Comment by salvadord** [comment]
I think can use `gidevector` in `pc.spike_record(gid, spiketimevector, gidvector)`to select a subset -- will look into it

**Comment by salvadord** [comment]
asked robert: using `pc.spike_record(gid, spiketimevector, gidvector)` you can select to record spks from only a subset of cells (instead of using -1 to record from all cells) … but do I need to call this function 1000s of times for each cell gid I want to record?

**Comment by salvadord** [comment]
Added support for recording spikes from only a subset of cells using e.g. cfg.recordCellsSpikes = ['E2']
