### ISSUE TITLE
Neuroml hdf5 import error

### ISSUE THREAD

**Issue by salvadord** [Neurosim-lab/netpyne#216]
User: "when I tried to run the very first tutorial I ran into an error. When it tries to load 'sim' from 'netpyne', I get the following error:

ImportError: No module named hdf5.DefaultNetworkHandler

I think it has something to do with import/export of NeuroML networks etc. I have NeuroML (especially pyNeuroML) installed. So I am not sure what the problem is. Do I have to update pyNeuroML? Is there a workaround, since I do not plan to convert/import to/from NeuroML at the moment?

Commenting out the 'from neuromlFuncs import *' line in 'sim.py' worked. If I am not going to use any NeuroML functionality, this workaround should not cause any problems, right?"

**Comment by pgleeson** [comment]
It's most likely to do with an earlier version of pyNeuroML. The latest is on PyPI, so you could just upgrade with:
   
    sudo pip install --upgrade pyneuroml
