### ISSUE TITLE
Save to .mat error

### ISSUE THREAD

**Issue by salvadord** [Neurosim-lab/netpyne#243]
e.g. with tut5.py:
TypeError: Could not convert (type <class 'netpyne.specs.ODict'>) to array

- don't get error locally on my laptop; but happens in Travis and neurosim machines

**Comment by rodriguez-facundo** [comment]
https://github.com/Neurosim-lab/netpyne/commit/7b75ba78f48385d4c4467d7926fd08b588fa2a02 is one month older than the issue and it makes substantial changes to saveMat. Not sure that fixed the issue cause I cannot login to neurosim machines. **Tried to reproduce locally but I couldn't.**
