### ISSUE TITLE
Source of spikes from multicomp cell is ~random segment if none named 'soma'

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#246]
[This code](https://github.com/Neurosim-lab/netpyne/blob/development/netpyne/cell.py#L543) in associateGid() for placing a NetConn which will be the source of spikes for that cell's gid:

```
 sec = self.secs['soma'] if 'soma' in self.secs else self.secs[self.secs.keys()[0]] # use soma if exists, otherwise 1st section
```

will try to select the 'first' section if there is none called 'soma'. However there is no guarantee that the key returned by self.secs.keys()[0] will be for the root section, it depends how the cell was created and how the list ordering is handled. 

It might be better to look through `self.secs` to find the section which has no parent (topol = {}) and use this:
```
 for s in self.secs:
     if len(self.secs[s]['topol'])==0: # i.e. no parent 
          sec = self.secs[s]
```

Thoughts @salvadord?

**Comment by salvadord** [comment]
yes! thats a great idea, thanks, I'll modify

**Comment by pgleeson** [comment]
Thanks. 

cc @andrisecker
