### ISSUE TITLE
randSample selection in convConn and divConn not ideal for small networks

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#254]
The [selection of a random sample](https://github.com/Neurosim-lab/netpyne/blob/development/netpyne/network.py#L834) from the pre/post population using:

    randSample = list(sim.unique([int(round(self.rand.uniform(0,len(preCellsTags)-1))) for i in range(4*convergence)])) # generate 4x and find unique list (to avoid duplicates)

can lead to errors for a small network/convergence size, as for e.g a population of 3 and a conv of 2 will not necessarily yield a list long enough for randSample[convergence] here

     preCellsSample[:] = [randSample[convergence] if x==postCellGid else x for x in preCellsSample] # remove post gid 

to exist. Also, there's no check that randSample[convergence] != postCellGid.

Same for divConn. There's also a finite chance for it happening for larger networks too.

**Comment by salvadord** [comment]
ah good point for small networks -- I will add a minimum value

randSample[convergence] will only be used if randSample contains postCellGid, and since all values in randSample are unique, that means that randSample[convergence] can't be postCellGid

**Comment by pgleeson** [comment]
Looks good. Thanks!
