### ISSUE TITLE
Should normal() and uniform() etc in expressions for delay etc. be specified with a seed?

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#256]
In this expression:

```
# Connectivity parameters
netParams.connParams['PYR->PYR'] = {
    'preConds': {'pop': 'PYR'}, 'postConds': {'pop': 'PYR'},
    'weight': 0.002,                    # weight of each connection
    'delay': '0.2+normal(13.0,1.4)',     # delay min=0.2, mean=13.0, var = 1.4
    'threshold': 10,                    # threshold
'convergence': 'uniform(1,15)'} 
```

the values for delay and convergence are picked randomly by Python during network construction. Normally these are generated the same every run. However, due to a recent change the values generated are different even though the same (default) seed is being used, see https://github.com/OpenSourceBrain/NetPyNEShowcase/commit/95a222366aced48a3cd6ab2553f1200a8f87ce4d generated from [this](https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/master/NetPyNE/HHSmall/HHSmall.py) etc.

This is probably down to these methods (or other random num generator methods) being called prior to generating the normal(13.0,1.4) etc.

**Comment by salvadord** [comment]
Padraig, I copied your code and ran it multiple times with 1, 2, 3 and 4 cores and always got an identical output file. 
Did you mean that the conn is different from that before making the last changes to netpyne? Or you specifically ran the same code (with the latest changes) multiple times and got different outputs?

**Comment by pgleeson** [comment]
@salvadord the former: there are different values generated for the weights and delays depending on the version of netpyne. This is probably down to making extra calls to random() (or other methods) in new versions. This could be solved by using a dedicated seeded instance of random.Random or np.random.RandomState and using that for these instead of the static/package level methods (so no other calls to the static methods would interfere with these calls).

**Comment by salvadord** [comment]
@pgleeson there is a dedicated h.Random() instance which gets initialized using the Random123() method, which takes 3 seeds. The reason to use h.Random.Random123() is that it has advantages over Python's random methods. To ensure independence of streams and reproducibility the h.Random() instance is initialized as a function of 1) the feature its being used for, 2) the pre- and or post-syn cells involved, 3) a user-defined seed. All 3 are needed to avoid repetition of patterns during connection/stim creation. 

The reason it changed with respect to prev netpyne versions is that I had to modify the implementation to fix bugs or improve it. I'm hoping this version will be stable now. 

You can see where the h.Random is initialized with the 3 seeds by searching for "Random123" in network.py: https://github.com/Neurosim-lab/netpyne/blob/development/netpyne/network.py

There are more details in these issues: 
https://github.com/Neurosim-lab/netpyne/issues/89
https://github.com/Neurosim-lab/netpyne/issues/185
