### ISSUE TITLE
dt is not properly set when using h.stdinit() aot h.init()

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#269]
When dt!=0.025, the value for dt set with h.stdinit() doesn't get properly set. Change was made at:

https://github.com/Neurosim-lab/netpyne/commit/db64b4b495b23788ec07d1e1a06b4b2bfd82bfd4#diff-a52fad7191c089fb6b67f5f3c6d75043L991

Try setting dt=0.01 in https://github.com/Neurosim-lab/netpyne/blob/master/examples/HHTut/HHTut.py to see this.

I suspect this is down to not setting steps_per_ms (or other variables) in addition to dt when it's changed...

**Comment by salvadord** [comment]
I changed to h.stdinit() cause otherwise h.v_init didn't get properly set ... I'm checking with Robert how to ensure both h.dt and h.v_init get set. thx

**Comment by salvadord** [comment]
aah ok, so seems like just need to set h.dt after calling h.stdinit(), otherwise gets reset  -- I'll update netpyne

**Comment by pgleeson** [comment]
Thanks, works fine for me now!
