### ISSUE TITLE
'xnorm'  and 'connList' conflict with each other

### ISSUE THREAD

**Issue by frodriguez4600** [Neurosim-lab/netpyne#287]
I have created a network with circular shape. I created it by passing a list of cell (each one with its own x,y,x position) to "popParams".
I conditioned into the "connParams" the cells that will be allowed to connect (using "connList" )as shown in the figure below:
![conn_with_connlist](https://user-images.githubusercontent.com/19541297/35390505-df79817c-01c2-11e8-82d8-382d440cec11.png)
This is the list of connections: connlist = [[0, 0],[0,2],[0,4],[0,6],[0,8]]

But then, if I also force a condition in 'xnorm' : [0,1], I get this figure:
![conn_with_connlist_and_xnorm](https://user-images.githubusercontent.com/19541297/35390603-31cc0314-01c3-11e8-9337-9af3c089f0eb.png)

Somehow, the connList is not been taking into account

**Comment by salvadord** [comment]
@frodriguez4600 Note that the indices specified in connList are relative to the subpopulation resulting from the conditions -- so if you apply and additional condition (such as xnorm: [0,1]) the indices in connList won't match the original ones, i.e. only the cells matching the conds are considered. let me know if that makes sense

**Comment by rodriguez-facundo** [comment]
Yeah, that's true. Thanks Salva
