### ISSUE TITLE
cellModel  VecStim spkTimes error reading a list 

### ISSUE THREAD

**Issue by JARS29** [Neurosim-lab/netpyne#288]
We are trying to implement an artificial cell using VecStim, following the example (http://www.neurosimlab.org/netpyne/reference.html?highlight=spkTimes):

spkTimes = range(0,1000,20) + [138, 155,270]

pulses = [{'start': 10, 'end': 100, 'rate': 200, 'noise': 0.5},
        {'start': 400, 'end': 500, 'rate': 1, 'noise': 0.0})]
netParams.popParams['artif3'] = {'cellModel': 'VecStim', 'numCells': 100, 'spkTimes': spkTimes, 'pulses': pulses}  # VecStim with spike times
But when we are running the script, an error arises :

Traceback (most recent call last):
  File "test.py", line 50, in <module>
    sim.createSimulateAnalyze(netParams, simConfig)
  File "/home/pablo/Downloads/netpyne/netpyne/wrappers.py", line 73, in createSimulateAnalyze
    (pops, cells, conns, stims, simData) = sim.create(netParams, simConfig, output=True)
  File "/home/pablo/Downloads/netpyne/netpyne/wrappers.py", line 27, in create
    cells = sim.net.createCells()                 # instantiate network cells based on defined populations
  File "/home/pablo/Downloads/netpyne/netpyne/network.py", line 76, in createCells
    newCells = ipop.createCells() # create cells for this pop using Pop method
  File "/home/pablo/Downloads/netpyne/netpyne/pop.py", line 58, in createCells
    cells = self.createCellsFixedNum()
  File "/home/pablo/Downloads/netpyne/netpyne/pop.py", line 137, in createCellsFixedNum
    cellTags['params']['spkTimes'] = self.tags['spkTimes'] # 1D list (same for all)
KeyError: 'params'

Could this possibly be a bug? pop.py has a try except statement on line 133, but the except only executes a pass. So then, how can we create an artificial cell importing spikes times from an external file (.mat file) ?

**Comment by salvadord** [comment]
to use VecStim you need to copy vecevent.mod and compile it with nrnivmodl

the file is here: https://github.com/Neurosim-lab/netpyne/blob/development/doc/source/code/mod/vecevent.mod
