### ISSUE TITLE
pyneuroml requirement triggers error

### ISSUE THREAD

**Issue by salvadord** [Neurosim-lab/netpyne#309]
@pgleeson I'm getting this after merging your changes. Can it be relaxed so it doesn't trigger an error if you don't have the right version?
 
 File "/usr/site/nrniv/local/python/netpyne/netpyne/neuromlFuncs.py", line 17, in <module>
    raise Exception('Error: pyNeuroML version %s is installed but at least v%s is required!'%(pynml_ver,min_pynml_ver_required))
Exception: Error: pyNeuroML version 0.3.4 is installed but at least v0.3.11 is required!

**Comment by pgleeson** [comment]
Will look into it.
For now, doing 'pip install --upgrade libneuroml' should fix your local error

**Comment by salvadord** [comment]
Thanks. 
Yes, the issue is in some workstations or HPCs users might not have permissions to update these libraries, so it would be better if it just disables neuroml conversion and shows a warning.

**Comment by pgleeson** [comment]
Ok, this PR should fix the issue: #311.

A better solution longer term might be to make pyNeuroML an explicit dependency, but let's see if this works for now...
