### ISSUE TITLE
Poster link results in 404

### ISSUE THREAD

**Issue by JustasB** [Neurosim-lab/netpyne#322]
The link in the repository readme appears to be broken: http://www.neurosimlab.com/salvadord/CNS16_poster.pdf

**Comment by salvadord** [comment]
Fixed, thanks!

**Comment by JustasB** [comment]
Sorry to bother you, the link still returns "page not found".

**Comment by salvadord** [comment]
I changed the link in the netpyne.org web to http://it.neurosim.downstate.edu/salvadord/CNS16_poster.pdf

let me know id u still have problems

**Comment by JustasB** [comment]
I see it. Thank you!
