### ISSUE TITLE
Speed check for panda dataframe with and without strings

### ISSUE THREAD

**Issue by wwlytton** [Neurosim-lab/netpyne#347]
needed by #349

**Comment by jjcarre** [comment]
Do we need to keep gid for lines like these:
spkgidColors = [gidColors[spkgid] for spkgid in spkgids]
        
spkinds = [sortedGids.index(gid)  for gid in spkgids]

**Comment by wwlytton** [comment]
let's see where spkgidColors is used - prob c=spkgidColors?

**Comment by wwlytton** [comment]
needed by #349
