### ISSUE TITLE
User error checking

### ISSUE THREAD

**Issue by salvadord** [Neurosim-lab/netpyne#35]
- [x] Check for valid syntax of netParams and simConfig
- [x] Check for missing or extra dict keys in netParams and simConfig (avoid default behaviors?)
- [x] Check for clashing rules
- [x] Avoid huge error printouts by using catching exceptions (?) or turning off notificatiosn

**Comment by salvadord** [comment]
Neuron allows you to set diam & L & then add pt3d points. Netpyne should allow only one or the other, and probably generate pt3d points if diam & L are used.

This is an example of the inconsistency that can occur: https://github.com/Neurosim-lab/netpyne/blob/d166081f664ce2e4c8ec96f1015c3e85acfa1c00/examples/HybridTut/HybridTut.py#L36

**Comment by barefoothiker** [comment]
*** flags
cfg.checkErrors - true or false (affects simFuncs initialize())
cfg.checkErrorsVerbose 
- True - prints evrything, passed and failed
- False - only failed, including warnings (nothing for passed)
*** add extra tests for numeric values eg. numCells
*** error messages not capitalized
XNormRange -> xnormRange etc
*** stop if an error happens
sys.exit
