### ISSUE TITLE
error trying to import model from json file

### ISSUE THREAD

**Issue by rodriguez-facundo** [Neurosim-lab/netpyne#367]
- error: 
line 69 in netpyne.sim.load.py is using object_hook to convert data loaded with JSON package. 
`data = json.load(fileObj, object_hook=_byteify)`
- Expected behaviour 
load a json file and save the strings as Unicode type
- Current behaviour:
load.json loads the dictionary, and applies the _bitify function leaving all Unicode text as binary type, resulting in no data being  accessible by the GUI
- NOTE: 
that works for python 2 because there is a difference between string and Unicode, but py3 adopted Unicode as standard

**Comment by salvadord** [comment]
probably will need to add a condition to check if running py2 or py3
