### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by salvadord** [Neurosim-lab/netpyne#37]
Test examples, tutorial code, and other repos -- M1, claustrum -- (if possible?)

**Comment by salvadord** [comment]
@pgleeson @adrianq  I'm having trouble setting up Travis, in particular installing the scipy python package -- tried several things, can you have a quick look if you get a chance? (maybe you see some obvious solution) thanks!

**Comment by pgleeson** [comment]
Have tried some things out on https://github.com/Neurosim-lab/netpyne/tree/travis_test, but for some reason these commits don't kick off Travis jobs. Maybe because I don't own the repo? @salvadord can you make a minor edit on that branch to see if it works for you?

**Comment by salvadord** [comment]
oh I turned off travis since wasn't working; just turned back on; also just about to push some changes. thanks for looking into it

**Comment by salvadord** [comment]
you can check travis output now: https://travis-ci.org/Neurosim-lab/netpyne 
get "ImportError: No module named scipy" even though its in the apt packages list.
other packages didnt seem to be available either, so I installed via pip, but scipy gives error via pip.
maybe missing some paths setup? what is needed in travis so apt packages available from python?
thanks
