### ISSUE TITLE
Mismatch in tut+example results when porting from py2 to py3 

### ISSUE THREAD

**Issue by salvadord** [Neurosim-lab/netpyne#372]
List of models that mismatch:
- tut2
- tut3
- M1

What to check:
- previous py3 also had same mismatch but I hadn't realized -- so not related to refactor
- check version of packages and libraries in py2 vs py3

**Comment by salvadord** [comment]
Unfortunately, the randomness of probabilistic conns in python2 depended on the ordering of dicts, see: https://github.com/Neurosim-lab/netpyne/blob/python2/netpyne/network/conn.py#L325

In python3 a major change is that dicts keep their insertion order: https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6

In summary, this means it's impossible to replicate python2 results in python3, due to essentially a bug in the python2 implementation, which introduced unreplicatable randomness for probabilistic connections. 

Nonetheless, it seems that within python2, results were replicated across environments, i.e. the same dict ordering was kept, although this property shouldn't be relied upon.

In python3 the ordering depends on insertion, so there is no need to make any changes.

**Comment by salvadord** [comment]
For tut2 and tut3 the results can be reproduced by starting to iterate the postCells dict by index 12 instead of 0. However, this rule doesn't fix tut5. Also, not sure if it applies to all python2 platforms:

"Python dictionaries and sets are stored using some efficient hashing algorithm. The precise algorithm is an implementation detail (and may differ from one version of Python to another as well as one platform to another (CPython, vs. PyPy, vs Jython or IronPython, and so on).

Iterating over the keys returns them in whatever order the underlying implementation chose to store them. Hashing provides for extremely efficient access to an item given its key. This typically has the effect of making them appear to be in a “random” order by human standards."

**Comment by salvadord** [comment]
Can try to set some fixed iteration order that at least reproduces python2 results in my platform

**Comment by jackdwyer** [comment]
[collections.OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict) might be useful if you are wanting to guarantee order

**Comment by salvadord** [comment]
Pattern doesn't follow simple rules -- could add rules to reproduce tuts and examples but too complex to implement for all cases, plus probably only applies to some platforms.

Added a flag in py2 branch to replicate previous results: cfg.useOldProbConn = True

**Comment by salvadord** [comment]
Had to made other fixes to ensure results were independent of the number of cores in Python3 (due to Python3 handling of dicts). Therefore I removed the cfg.useOldProbConn and just added to CHANGES.md:

NOTE on backward replicability: Due to several performance improvements and bug fixes to ensure future replicability in both Python 2 and 3, it won't be possible to replicate results of previous versions.
