### ISSUE TITLE
Not all batch simulations complete

### ISSUE THREAD

**Issue by joewgraham** [Neurosim-lab/netpyne#412]
When running a batch of simulations, not all of them complete. 

In the batch tutorial (http://www.netpyne.org/tutorial.html#running-batch-simulations-tutorial-8), for example, there are two parameters varied and three values for each parameter, for a total of 9 simulations.  But only the first 6 get run (0_0, 0_1, 0_2, 1_0, 1_1, 1_2) and then the terminal just sits at the Python prompt.  (Missing sims 2_0, 2_1, 2_2)

The following commands should reproduce the problem:
```
cd ~ 
mkdir netpyne_batch_tut 
cd netpyne_batch_tut 
curl -O http://www.netpyne.org/_downloads/11bf4e0a6395bbf144b644269a25b8be/tut8_netParams.py 
curl -O http://www.netpyne.org/_downloads/07e5be985bfca5ede59f15f8e38eb289/tut8_cfg.py 
curl -O http://www.netpyne.org/_downloads/473a938270d9e719882bd861fcb1e8b9/tut8_init.py 
curl -O http://www.netpyne.org/_downloads/a023a2e3de0d562f75dbf29656110821/tut8_batch.py 
mpiexec -np 4 nrniv -python -mpi tut8_batch.py
```

**Comment by joewgraham** [comment]
The output will appear in a dir called `tut8_data`.  Rasters and traces for the final three sims will be missing if this reproduces my problem.

**Comment by salvadord** [comment]
thanks joe. So it works correctly in py2, but I was able to reproduce the issue in py3 -- although only missing 2_1 and 2_2 in my case. I think it's related to terminating before it has time to finish. Will keep digging.

**Comment by salvadord** [comment]
fixed, had to add a command to wait for completion
