### ISSUE TITLE
plotSpikeStats confuses 'allCells' and 1st pop of 'eachPop'

### ISSUE THREAD

**Issue by salvadord** [Neurosim-lab/netpyne#414]
I have tried to use the spikeStats analysis.
It make an error if called with:
analysis.plotSpikeStats (include = [‘allCells’, ‘eachPop’], timeRange = None, graphType=’boxplot’, stats = [‘rate’, ‘isicv’], popColors = [], figSize = (6,8), saveData = None, saveFig = None, showFig = True)

It confuses allCells and the first pop of eachPop in the vertical axis of the box plot.
I can only guess that the correct boxplot for allCells in the one on the top.

I'm using the netpyne 0.9.1.3.

**Comment by salvadord** [comment]
@jjcarre this bug is fixed right?

**Comment by jjcarre** [comment]
I don't see a pull request associated with this issue, but I'm unable to recreate the issue

**Comment by salvadord** [comment]
thx ...did you try with tut5.py?

**Comment by jjcarre** [comment]
just tried tut5 here are the graphs it made, let me know if this isn't the desired result
![model_output_spikeStat_boxplot_rate](https://user-
![model_output_spikeStat_boxplot_isicv](https://user-images.githubusercontent.com/23328106/69983155-a2450300-14fb-11ea-8177-0f9249cdd6e6.png)
images.githubusercontent.com/23328106/69983144-9a855e80-14fb-11ea-80a0-b2bba965a4fd.png)

**Comment by salvadord** [comment]
yes that looks correct. thanks for testing this. I'll close issue  for now since looks magically solved :) thx!
