### ISSUE TITLE
Add a web section explaining how to contribute to NetPyNE

### ISSUE THREAD

**Issue by salvadord** [Neurosim-lab/netpyne#426]
use MNE as example: http://martinos.org/mne/stable/contributing.html

also UNICEF magicbox example: https://github.com/unicef/magicbox/blob/master/README.md

**Comment by jasmainak** [comment]
If I may add ...

- make code pep8 compliant, specially the CamelCase hurts my eye :)
- add numpy docstrings
- be explicit about dependencies in readme
- document API using sphinx autodoc

It may seem like an annoyance now but it will pay off in the long run

**Comment by salvadord** [comment]
Thanks Mainak! Yes, will definitely work towards all these. I did have another related issue for some of them: https://github.com/Neurosim-lab/netpyne/issues/200

I was looking at the MNE package and it's very impressive how it's all nicely organized and documented. Will work to move NetPyNE towards that ... thanks again!

**Comment by ariel-brassesco** [comment]
Hi Guys! I am working in a draft. I am trying to finish soon.

**Comment by salvadord** [comment]
useful info - https://journals.plos.org/ploscompbiol/article?id=10.1371%2Fjournal.pcbi.1007296
