### ISSUE TITLE
framework.py vs. __init__.py

### ISSUE THREAD

**Issue by cliffckerr** [Neurosim-lab/netpyne#5]
Just a thought -- maybe instead of framework.py, you could use relative imports in __init__.py to achieve the same result? Then instead of e.g.
`import framework as f`
you could have something like
`import netpyne as N`
and then this would work both inside and outside of the repository. For an example see

https://github.com/optimamodel/Optima/blob/cleaned-up-imports/optima/__init__.py

To do this `__init__.py` would simply be:
```
from . import sim
from . import analysis
from .network import Network
from .cell import Cell, PointNeuron, Pop 
from . import utils
from . import default

import pylab
```

**Comment by salvadord** [comment]
so each of the modules (eg. sim, network or analysis) import framework to have access to other modules -- would this work with the __init__.py method?

I cant access https://github.com/optimamodel/Optima/blob/cleaned-up-imports/optima/__init__.py

thanks

**Comment by salvadord** [comment]
ok found a way around it -- all sim functions are now in simFunc.py; framework.py is renamed as sim.py and imports all simFuncs, as well as all other modules. 
So now everything is accessed via sim
