### ISSUE TITLE
cfg issue

### ISSUE THREAD

**Issue by karnigili** [Neurosim-lab/netpyne#518]
I am running tut8  (btw, thanks for adding a grid-search functionality!)

However, I get this error:

```
cfg = specs.simConfig()
TypeError: 'module' object is not callable
```

What is going wrong?

Thanks!

**Comment by cliffckerr** [comment]
@karnigili The real devs can give a better answer :) But the short answer is that you need one more layer in the import:
```
>>> import netpyne
>>> cfg = netpyne.specs.simConfig.SimConfig()
>>> cfg
<netpyne.specs.simConfig.SimConfig object at 0x7f52d47b8b50>
```

**Comment by salvadord** [comment]
hi Gili ... you were only missing the capital 'S', since SimConfig is a class:

``
from netpyne import sim, specs
cfg = specs.SimConfig()
``

**Comment by karnigili** [comment]
@salvadord thank you!
