### ISSUE TITLE
[documentation] Markdown format on PyPI description

### ISSUE THREAD

**Issue by Helveg** [Neurosim-lab/netpyne#525]
On PyPI your [project description ](https://pypi.org/project/netpyne/)is in MD but not parsed as such. There are a few possible reasons IIRC:

* You either did not set the "long-description content-type" or such in setup.py
* You're packaging it with an old version of setuptools/wheels/twine; I think it was versions before setuptools v0.40.0 that suffered from this

**Comment by joewgraham** [comment]
Thanks! I added a "long-description content-type" in setup.py and that seems to have fixed the problem.
https://pypi.org/project/netpyne/
