### ISSUE TITLE
[Bug report] missing `aux_fun.inc` file in `doc/source/code/mod` folder?

### ISSUE THREAD

**Issue by sanjayankur31** [Neurosim-lab/netpyne#528]
**Describe the bug**

I was following the steps in the .travis.yml file to test my installation
https://github.com/Neurosim-lab/netpyne/blob/development/.travis.yml#L66

and run into this error:

```
$ nrnivmodl mod/
..
..
Translating iholmw.mod into iholmw.c
MODLUNIT=/usr/share/nrn/lib/nrnunits.lib \
  /usr/bin/nocmodl izhi2003b.mod
Thread Safe
Couldn't open: aux_fun.inc
Couldn't open aux_fun.inc
make: *** [/usr/bin/nrnmech_makefile:93: x86_64/iholmw.c] Error 1
make: *** Waiting for unfinished jobs....

```

It appears this file includes `aux_fun.inc` which isn't available there:

https://github.com/Neurosim-lab/netpyne/blob/development/doc/source/code/mod/iholmw.mod#L65

**Reproducing the bug**

1. Run `nrnivnmodl mod` in the `doc/source/code/` directory

**Expected behavior**

The command should complete

**System information**

- OS and version: Fedora 32
 - NetPyNE version: 0.9.7
 - NEURON version: 7.8.1
 - Python version: 3.9.0rc2

**Additional context**

NA

**Comment by joewgraham** [comment]
Sorry for the oversight!  I have added aux_fun.inc to doc/source/code/mod
https://github.com/Neurosim-lab/netpyne/blob/development/doc/source/code/mod/aux_fun.inc
