### ISSUE TITLE
[question] e-mail responses blocked on google group

### ISSUE THREAD

**Issue by sanjayankur31** [Neurosim-lab/netpyne#529]
Hello!

I replied to a thread on the google-group and got a bounce saying that e-mail postings were not permitted to it.

```
The group netpyne-forum@googlegroups.com does not allow posting through email.
```

If this is a conscious decision, could this please be revisited? It's a lot easier to manage all our mailing lists through e-mail than it is by visiting their web-interfaces individually to reply.

Cheers!

**Comment by joewgraham** [comment]
Thanks for pointing this out!  I have changed the settings to allow posts by email.

**Comment by sanjayankur31** [comment]
Thanks very much @joewgraham .
