### ISSUE TITLE
[Bug report][enhancement] sim.checkOutput() does not provide real output information

### ISSUE THREAD

**Issue by jpalma-espinosa** [Neurosim-lab/netpyne#608]
**Describe the bug**

Mismatch: model tut2 numSpikes is 400 but expected value is 931

**Reproducing the bug**

1. Download and Open 'tut2.py'
2. Run the example. It will work smoothly
3. Change ```netParams.stimSourceParams['bkg'] = {'type': 'NetStim', 'rate': 10, 'noise': 0.5}``` to ```netParams.stimSourceParams['bkg'] = {'type': 'NetStim', 'rate': 10, 'noise': 0}```(i.e., change the noise)
4. Plots are generated but the error is raised

**Expected behavior**

I would expect that checkOutput would do a revision of my simulation parameters or something more insightful regarding the output, as the name suggests
**System information**

- OS and version: macOS Catalina (macbook pro mid 2012)
 - NetPyNE version: 1.0.0.2
 - NEURON version:  7.8.2 HEAD (09b151ec) 2020-12-16
 - Python version: 3.9.3

**Additional context**

Checking the implementation of ```sim.checkOutput('tut2')```, it only serves for replicating the exact same experiment. It does not provide any more help, nor information regarding the simulation output.
I feel that this function does not provide enough information if one wants to test or play around with the tutorials, as this output (and for other tutorials) is fixed. Also, this behavior is not explained in the tutorial webpage

**Comment by joewgraham** [comment]
Hi @jpalma-espinosa , thanks for the bug report.  The function sim.checkOutput is only meant to be used internally by NetPyNE (for code testing/continuous integration).  

I added a docstring to checkOutput and added a comment explaining its purpose to each tutorial and example where it was utilized.
