### ISSUE TITLE
What are the available keys in the dictionary of ions?

### ISSUE THREAD

**Issue by lungsi** [Neurosim-lab/netpyne#626]
The [documentation](http://netpyne.org/reference.html?) says

> ions: Dictionary of ions.
The key contains the name of the ion (e.g. ‘na’ or ‘k’) The value contains a dictionary with the properties of the ion (e.g. {'e': -70}).

But, what are all the possible parameters (apart from `"e"`) one can use in the dictionary of ions?

**Comment by joewgraham** [comment]
Hi @lungsi , thanks for the question.  I have updated the documentation to include the parameters available for 'ions' in a 'sec'.  Note that setting ion properties in a section only affects the ion properties in that section.

ions: Dictionary of ions.
The key contains the name of the ion (e.g. ‘na’ or ‘k’) The value contains a dictionary with the properties of the ion for the particular section (e.g. {'e': -70}). Properties available are 'e': reversal potential, 'i': internal concentration of the ion at that section, and 'o': the extracellular concentration of the ion at that section.
