### ISSUE TITLE
Update documentation for new location of mod files

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne#7]
The mod directory has moved, to the documentation folder.

Install instructions should be updated to make it easier to find and compile these to get the HybridTut_run.py example to run. Or alternatively, copy izhi2007a.mod etc. to https://github.com/Neurosim-lab/netpyne/tree/master/examples

**Comment by salvadord** [comment]
I moved each example into a separate folder with the required mod files -- future examples might require multiple files so better to have them in separate subfolders.
thanks
